Add support for fonts preview files ttf, otf and woff
Preview for fonts using fontpreview, it is necesary to install the magick packge included in the ImagiMagick version 7

diff --git a/scripts/vimg b/scripts/vimg
--- a/scripts/vimg
+++ b/scripts/vimg
@@ -77,10 +77,24 @@ function epubpreview {
   render_at_size "${1}" "${2}" "${converted_epub_img_path}"
 }
 
+function fontimagepreview {
+  if ! command -v fontpreview &> /dev/null; then
+      printf "fontpreview could not be found in your PATH.\n\nPlease install it to display font previews."
+     exit
+  fi
+  readonly converted_font_img_path="${TMP_FOLDER}/fontpreview-convert.png"
+  img_path="${3}"
+  error_message=$(fontpreview -i "${img_path}" -o "${converted_font_img_path}" 2>&1)
+  if [ $? -ne 0 ]; then
+    printf "Cann't convert the file, check if the file have a password, error: %s" "$error_message"
+    exit
+  fi
+  render_at_size "${1}" "${2}" "${converted_font_img_path}"
+}
 
 function parse_options {
     extension="${1##*.}"
-    echo -e "Loading preview..\nFile: $1 \n"
+    echo -e "Loading preview...\nFile: $1 \n"
     case $extension in
     jpg | png | jpeg | webp)
         render_at_size $4 $5 "$1"
@@ -105,9 +119,12 @@ function parse_options {
     epub)
         epubpreview $4 $5 "$1"
     ;;
+    ttf | otf | woff)
+        fontimagepreview $4 $5 "$1"
+    ;;
 
     *)
-    echo -n "unknown file $1"
+    echo -n "unknown file type path:\n$1"
     ;;
     esac
 }
